spring.application.name=24_microservicio_formacion
server.port= 9005
server.servlet.context-path=/formacion

remote.url=http://localhost:8005/escuela/

remote.user=admin
remote.password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/SpringRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak.clientId=springclient