 # Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: servicio-alumnos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev 
server:
  port: 8005
  servlet:
    context-path: /escuela
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/alumnoscursos
    username: root
    password: root
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${HOST_DB}:${PORT_DB}/alumnoscursos
    username: ${USER_DB}
    password: ${PASS_DB}
