apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # o el namespace donde está tu pod
  name: read-services
rules:
- apiGroups: [""]
  resources: ["services","endpoints"]
  verbs: ["get", "list", "watch"]