apiVersion: v1
kind: Service
metadata:
  name: formacion-service
spec:
  selector:
    app: formacion
  type: LoadBalancer  # Hace accesible el servicio desde fuera del clúster
  ports:
    - protocol: TCP
      port: 10000      # Puerto del servicio en Kubernetes
      targetPort: 9005 # Puerto del contenedor
      nodePort: 30002   # Puerto en la máquina física (Minikube/Kubernetes lo expone aquí)